canonical/pgbouncer-k8s-operator

.github/pull_request_template.md

PR templates have proved useful in other operator repos, so one should be added to this repo. 
- This is a flexible guideline, and not a rigidly defined document. It should remain mutable by PR authors to minimise time spent reading and writing unnecessary filler.

DPE-108  Add PR template 

---

.github/workflows/ci.yaml
actions.yaml
src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

The user management previously implemented in this charm is unnecessary, and has been removed. This PR is separate from the rest of the k8s charm update work to make it easier to review. 
This code was written when I had a worse understanding of the intended purpose of this charm. Postgres/pgbouncer users shouldn't be managed directly by the pgbouncer charm user; instead, they should be derived from the postgres charm relation. Therefore, this code is unnecessary. 
The failing integration tests are due to the docker image not being available on github; a future PR will fix this. 
- Removed the following user management actions, as well as their associated tests:
- change_password
- add_user
- remove_user
- get_users
- Removed irrelevant unit & integration tests. Remaining unit & …

Removed unnecessary user management

---

.github/workflows/release.yaml

Have auto release use a pinned revision of pgbouncer oci image.
Because we don't have pgbouncer rock in place yet (e.g. image published to official canonical channels).

image override to pin uploaded revision

---

.github/workflows/release.yaml

Release.yaml doesn't use the correct juju version to get around the scale-down bug. This PR fixes that.

fixed release CI to use correct juju version

---

src/charm.py
src/relations/backend_database.py
src/relations/db.py
src/relations/peers.py
tests/unit/relations/test_backend_database.py
tests/unit/relations/test_db.py
tests/unit/relations/test_peers.py
tests/unit/test_charm.py

Fixes endpoints to point to the correct units when scaling. 
I forgot to update how master/standby endpoints are updated when adding scaling. This PR adds that in. 
Updated unit tests, integration tests all pass fine.

Fix endpoints to point to correct units when scaling

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
CONTRIBUTING.md
metadata.yaml

The `pgbouncer:latest` container has been updated to jammy, so this is a quick PR to pin this to the new pinned focal version. 
PR is currently running tests, but there are no meaningful changes in this container between the previous focal version, other than no pgbackrest.

set pgbouncer container to focal branch

---

.github/workflows/release.yaml
src/charm.py
src/constants.py
tests/integration/helpers/helpers.py
tests/integration/relations/test_backend_database.py
tests/integration/relations/test_db.py
tests/integration/relations/test_db_admin.py
tests/integration/test_charm.py
tests/unit/test_charm.py

This PR uses pebble to implement multiple pgbouncer instances. 
Pgbouncer is single-threaded. The accepted way to make use of this is to have multiple pgbouncer instances - one per core. On kubernetes, this could also be mitigated by only deploying containers with one CPU core.
- Implements multiple pgbouncer instances, one per core on each unit.
- Added an integrated test that verifies the instances are all running as expected.

Multiple pgbouncer application instances in pebble

---

.github/workflows/ci.yaml
documentation/reference/charm.md
pyproject.toml
src/charm.py
tests/integration/helpers/helpers.py
tests/integration/relations/test_peers.py
tests/integration/test_tls.py
tests/unit/test_charm.py
tox.ini

* [DPE-558](https://warthogs.atlassian.net/browse/DPE-558)
* Implement handlers necessary for the postgresql_tls library to enable and disable TLS
* charm should be able to scale up and restart with TLS enabled
* TLS relations implementation
* Added unit tests for TLS changes
* Basic TLS integration test
[DPE-558]: https://warthogs.atlassian.net/browse/DPE-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TLS relations implementation

---

lib/charms/pgbouncer_k8s/v0/pgb.py
tests/integration/relations/test_db.py

Jira issue: [DPE-1037](https://warthogs.atlassian.net/browse/DPE-1037)
OpenLDAP fails with an error when related to the PgBouncer charm.
```
openldap/0*       error     idle   10.1.150.242  389/TCP  crash loop backoff: back-off 5m0s restarting failed container=openldap pod=openldap-5449dfd7cb-jslhn_microk8s(a795f914-79b3-48f4-9b80-4dfbb4234025)
```
The error is due to some parameters not supported by PgBouncer. As PgBouncer offer the possibility to ignore unsupported parameters by listing them on the `ignore_startup_parameters` field from the PgBouncer config file, it was added there.
Ignore OpenLDAP charm `options` parameter.
Tested manually and saw that the charm is deployed correctly and no error happens (haven't checked too deep to see the where the unsupported parameters are used …

Fix relation with OpenLDAP

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Jira ticket: [DPE-1232](https://warthogs.atlassian.net/browse/DPE-1232)
Enable the process that releases new libraries versions to Charmhub and check outdated libraries on PRs.
Similar to what was implemented on https://github.com/canonical/postgresql-k8s-operator/pull/84.
Move libraries check to ci.yaml and add libraries release step.
[DPE-1232]: https://warthogs.atlassian.net/browse/DPE-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move libraries check to ci.yaml and add libraries release step

---

.github/workflows/release.yaml
CONTRIBUTING.md
charmcraft.yaml
tests/integration/helpers/helpers.py
tests/integration/relations/pgbouncer_provider/application-charm/charmcraft.yaml
tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
tests/integration/relations/test_backend_database.py
tests/integration/relations/test_db.py
tests/integration/relations/test_db_admin.py
tests/integration/relations/test_peers.py
tests/integration/test_charm.py
tests/integration/test_tls.py

Jira issue: [DPE-1480](https://warthogs.atlassian.net/browse/DPE-1480)
The charm is still on Focal (and the OCI image is already on Jammy).
Upgrade all the bases and all the deployments to use Jammy.
The TLS Certificates Operator deployed in the tests had its channel changed to stable, as now we have it.
Used the existing tests to confirm that the charm works on Jammy.
Upgrade charm to Jammy.
[DPE-1480]: https://warthogs.atlassian.net/browse/DPE-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade to jammy

---

metadata.yaml

Security scan report:
```
Revision r61 (amd64; channels: 14/edge)
* libc-ares2: 6164-1
```
Rebuild and update rock

Update OCI due to outdated packages

---

charmcraft.yaml
renovate.json
src/charm.py
src/constants.py
src/relations/db.py
tests/integration/relations/test_db.py

Pgbouncer would block when a legacy relation requests  extensions even if they are enabled in the backend Postgresql DB
Check for extensions in the backend relation and block accordingly

[DPE-2056] PGB extensions support

---

metadata.yaml
src/charm.py
src/relations/backend_database.py
tests/integration/relations/test_db.py
tests/unit/relations/test_backend_database.py

Connection to PgBouncer in a cross-model relation (with PostgreSQL VM charm) is not working due to different password encryption algorithms used.
Implement the same approach from https://github.com/canonical/pgbouncer-operator/pull/56 to fix it. One adjustment was made in the charm to avoid overriding the blocked status related to the extensions message.
Also, on https://github.com/canonical/postgresql-k8s-operator/pull/215 the password encryption was changed on PostgreSQL k8s charm to improve security.
Currently, the unique options to improve the security of the password of the PgBouncer auth user is to use something like SSL certificates (as mentioned on https://github.com/pgbouncer/pgbouncer/issues/774#issuecomment-1305769441). The other approaches mentioned in the same comment are …

[DPE-2334] Use hashed password for auth user

---

src/charm.py
tests/integration/relations/pgbouncer_provider/helpers.py
tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py

When the PgBlouncer charm pod is deleted, the auth file is not re-rendered, causing connection issues.
Re-render the auth file in the `upgrade-charm` hook, which is executed after a pod is rescheduled (like when we manually delete the pod).
Also added a check in the `on-start` hook, that is the hook that fires when the host machine is restarted (like when the Multipass VM is restarted).
Fixes https://github.com/canonical/pgbouncer-k8s-operator/issues/133.

[DPE-2406] Fix pod deletion

---

metadata.yaml
tests/integration/relations/test_backend_database.py
tests/integration/relations/test_db.py
tests/integration/test_tls.py

Security notice:
```
Revision r78 (amd64; channels: 14/edge)
* locales: 6409-1
```

[MISC] Update rock due to outdated packages

---

metadata.yaml

* documentation on Discourse was missing
* metadata.yaml was outdated (missing lings, outdated year, wrong summary, etc)
We are preparing the charm for release to stable and need to
generate all the necessary documentation/links on https://charmhub.io/pgbouncer-k8s
* update metadata.yaml to match pgbouncer-k8s concepts
* add Discourse documentation Overview page
* Also sync all SQL charms layout in metadata.yaml

DPE-2753 Add Discourse documentation + update metadata.yaml

---

src/charm.py
tests/unit/test_charm.py

Ports are not patched on the K8s service.
Use open port call from ops if available, patch directly if not.

[DPE-2565] Open port

---

.github/workflows/ci.yaml
.github/workflows/lib-check.yaml
.github/workflows/release.yaml
lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/data_platform_libs/v0/upgrade.py
lib/charms/postgresql_k8s/v0/postgresql.py
tests/integration/helpers/postgresql_helpers.py
tests/integration/relations/test_backend_database.py
tests/integration/relations/test_db.py

A number of tests drifted underneath the repo
* Fix failing tests
* Split off check lib

[DPE-2804] Tweak tests

---

README.md

Closes https://github.com/canonical/pgbouncer-k8s-operator/issues/148
Update the readme to reference the correct endpoint

[DPE-2676] Update readme to reflect the actual readonly endpoint

---

.github/workflows/ci.yaml
.github/workflows/lib-check.yaml
.github/workflows/release.yaml
.github/workflows/sync_issue_to_jira.yaml
CONTRIBUTING.md
charmcraft.yaml
poetry.lock
pyproject.toml
tox.ini

Charmcraft strict dependencies break release libraries action
* Regenerate `requirements.txt` the same way as for the check lib workflow
* Update dpw to 9.0.2

[MISC] Fix release libraries

---

.github/workflows/ci.yaml
src/charm.py

Copy Juju 3.1.7 fix from the mongo charm, so that we can deploy without downgrading the agent.

[MISC] Copy 3.1.7 fix from Mongo

---

src/charm.py
src/relations/peers.py
tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
tests/unit/test_charm.py

Peer secrets were set as peer data.

[MISC] Fix secret keys

---

tests/integration/test_upgrade_from_stable.py

Switching the upgrade test to use `1/stable`

[MISC] Upgrade from stable branch

---

lib/charms/postgresql_k8s/v0/postgresql.py
src/charm.py
src/relations/backend_database.py
src/relations/db.py
src/relations/pgbouncer_provider.py
tests/integration/relations/test_db.py
tests/unit/relations/test_db.py
tests/unit/relations/test_pgbouncer_provider.py

Fixing bugs noticed during switching the VM charm to templates.

[MISC] Bugfixes

---

src/charm.py
src/relations/pgbouncer_provider.py
tests/integration/relations/pgbouncer_provider/helpers.py
tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
tests/unit/relations/test_pgbouncer_provider.py

Removes the need for `patch_port()` at `pebble-ready` event. There is no reason to check if we need to patch the port at this event, as port should be toggled to ClusterIP / NodePort in response to client relations exclusively. Also, pebble-ready happens at every restart of the pod, which per-se does not mark as a change on exposing or not the service.
Simplifying the `external_connectivity()` to make it more readable and adding extra safeguards in the relation checking methods for node-port.
Fixes the tests to consider NodePort *or* ClusterIP accordingly.

Fix deletion test

---

src/charm.py

Tested on https://github.com/canonical/data-integrator/pull/49
Looks like the issue was indeed the metrics service.

[MISC] Don't autostart metrics service if password is not yet set

---

lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/relations/backend_database.py

Auth query functions are not readded when backend rerelates
Collect existing client rel dbs and add or remove auth_query function on backend rel events
Port of https://github.com/canonical/pgbouncer-operator/pull/224

[DPE-4221] Recreate auth_query on backend rerelation

---

lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/postgresql_k8s/v0/postgresql.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/charm.py
src/relations/db.py
src/relations/pgbouncer_provider.py
tests/unit/relations/test_db.py
tests/unit/relations/test_pgbouncer_provider.py

Cannot drop db objects when rerelating to pgbouncer
* Pass relations to create_database
* Update charm libs

[DPE-1454] Update database ownership

---

CONTRIBUTING.md
LICENSE

Addressing reviewer comments from #283 as part of preparation for making pgbouncer-k8s charm listed on charmhub.io
Update with new information the contact link at CONTRIBUTING and fix LICENSE Copyright notice with Canonical Ltd as owner.

[DPE-3991] Update old information on CONTRIBUTING and LICENSE

---

LICENSE

This reverts the LICENSE file change introduced by this commit: 801cb1569fb479f738b0161336ec743768c0301d

[DPE-4423] Revert update LICENSE file

---

.github/workflows/ci.yaml
lib/charms/tempo_k8s/v2/tracing.py

Forgot to add the actual comment annotation

[MISC] Renovate microk8s

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/sync_issue_to_jira.yaml
poetry.lock
pyproject.toml
tox.ini

Requires update to tox.ini build wrapper

Update data-platform-workflows to v16.2.0

---

src/charm.py
tests/integration/test_trust.py
tests/unit/test_charm.py

K8s charms that create resources in a RBAC enabled environment need to be deployed with the `--trust` flag, otherwise they don't work. If a user deploys PGB k8s charm without that flag, there is no clear message indicating the issue.
- Adds a integration test to see if charm enters blocked status if not deployed with `--trust`.
- Adds a check in K8s resource creation functions to catch for 403 forbidden errors. ==> This check was added everywhere `lightkube.Client().get` is used. Maybe overkill, but better safe than sorry, I think?
- Adds unit tests

[DPE-4062] Improve displayed error message if charm was deployed without `--trust` flag

---

.github/renovate.json5
.github/workflows/ci.yaml
lib/charms/postgresql_k8s/v0/postgresql.py
lib/charms/tempo_k8s/v1/charm_tracing.py

* Converge on shared renovate config.
* Update charm libraries

[MISC] Use preset renovate configuration

---

.github/workflows/sync_docs.yaml

A [new `sync_docs.yaml` workflow](https://github.com/canonical/data-platform-workflows/pull/220) was released in data-platform-workflows `v19.2.0`. It overwrites the old experimental `_sync_docs.yaml` workflow and releases it to the public interface.
This PR corrects the filename to match the new syntax without the experimental `_` prefix.

Update sync_docs.yaml to new version

---

lib/charms/data_platform_libs/v0/data_interfaces.py
src/charm.py
src/relations/pgbouncer_provider.py
tests/unit/relations/test_pgbouncer_provider.py

Port of https://github.com/canonical/pgbouncer-operator/pull/373
* Update libs
* Removes an OPS import warning
* Fixes wrong emission of `database_created` due to creating the secret before the requirer sets the requested database (data-integrator)

[MISC] Don't set secrets until db is set

---

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
lib/charms/tempo_coordinator_k8s/v0/tracing.py
pyproject.toml
src/charm.py
tests/unit/conftest.py

There are a bunch of tempo tracing related updates:
1. tempo-k8s has been deprecated in favor of tempo ha
2. tracing charm libs need to be fetch-ed from tempo_coordinator_k8s
3. tracing traffic is now relayed through grafana-agent-k8s (like the remaining COS traffic)
2. update tracing charm libs from new repo
Test integration with tempo ha + test relay of traffic through grafana-agent-k8s
Update pgbouncer-k8s tracing related documentation (in progress)

[DPE-5312] Integrate with Tempo HA + test relay support of tracing traffic through grafana-agent-k8s

---

src/charm.py
tests/integration/test_expose_external.py

[ServiceSpec](https://gtsystem.github.io/lightkube-models/1.32/models/core_v1/#servicespec) does not have a property `name`
Fix access to `service.spec.type`
Also, ensure nodeport_endpoints are different than load_balancer_endpoints in test_expose_external.py

Fix minor typo in access of ServiceSpec object

---

tests/integration/test_upgrade_data_integrator.py

Await config change during data integrator upgrade test

[MISC] Await config change

---

lib/charms/postgresql_k8s/v0/postgresql.py
src/charm.py
src/relations/pgbouncer_provider.py
tests/unit/relations/test_pgbouncer_provider.py

This PR contains a slight refactor to sync code with PostgreSQL VM / K8s operator codebases.
Changes:
- Start leveraging PostgreSQL lib `PERMISSIONS_GROUP_ADMIN` constant.
- Start passing PostgreSQL lib create-user `extra_user_roles` argument  as a list.

[MISC] Sanitize PostgreSQL extra-user-roles arg
