src/charm.py, src/constants.py, tests/unit/test_charm.py, tox.ini
adds user group when running pgbouncer through pebble
- Updated unit test to match.
=> Add group to pebble layer.

.github/workflows/release.yaml
Resource version number has to be a simple integer
=> update container resource version

tox.ini
=> Unpin flake8

lib/charms/postgresql_k8s/v0/postgresql_tls.py, src/relations/pgbouncer_provider.py
Adding the database field in the provider side. This is to follow the interface signature change https://github.com/canonical/charm-relation-interfaces/pull/43
=> [MISC] Add database field in the provider-side databag

src/charm.py, tests/unit/test_charm.py
* [DPE-1514](https://warthogs.atlassian.net/browse/DPE-1514)
* Sets the workload version to what Pgbouncer reports as it's version
* Version is parsed from calling `pgbouncer --version`
* Alternatively we can get the version from apt, but that is likely to change once we switch to a Rock image
* I don't think it is possible to have different unit and app version
* Sets the workload version
[DPE-1514]: https://warthogs.atlassian.net/browse/DPE-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set workload version to PGB version

poetry.lock, tests/integration/relations/test_backend_database.py
The backend test is actually broken, not just flaky due to CI
Also updated the poetry lock, some people claim it helps with the legacy build system failure
=> Fix main branch

lib/charms/postgresql_k8s/v0/postgresql.py, metadata.yaml, tests/integration/relations/pgbouncer_provider/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
Security notification:
```
Revision r57 (amd64; channels: 14/edge)
* libperl5.34: 6112-2
* libpython3.10: 6139-1
* perl: 6112-2
* perl-modules-5.34: 6112-2
```
* Bump the OCI to update the packages
* Update charm libs
=> Update OCI due to outadate pkgs

metadata.yaml
Security scan report:
```
Revision r60 (amd64; channels: 14/edge)
* python3-requests: 6155-1
```
Rebuild and update rock
=> Update Rock due to outdated packages

metadata.yaml
Switch to PPA PGB prometheus exporter
=> [DPE-2259] Switch to PPA exporter

.github/workflows/ci.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, tests/integration/relations/pgbouncer_provider/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
Update microk8s branch and charm libs.
=> [MISC] Update microk8s to 1.28

metadata.yaml
Security notice:
```
Revision r68 (amd64; channels: 14/edge)
* libpq5: 6296-1
* postgresql-14: 6296-1
* postgresql-client-14: 6296-1
* postgresql-plpython3-14: 6296-1
```
=> [MISC] Update rock due to outdated packages

tests/integration/relations/test_backend_database.py
Postgresql log location changed.
Update the test to look at the right place for TLS connection.
=> [MISC] Fix backend tests

.github/workflows/ci.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/postgresql_k8s/v0/postgresql.py, src/relations/backend_database.py, tests/integration/helpers/helpers.py, tests/integration/relations/pgbouncer_provider/helpers.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
Not using relation secrets
* Update data_interfaces to version that supports secrets
* Tweak tests
=> [DPE-2296] relation secrets

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/data_platform_libs/v0/upgrade.py, lib/charms/postgresql_k8s/v0/postgresql.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/relations/test_backend_database.py, tests/integration/relations/test_db.py, tests/integration/relations/test_db_admin.py, tests/integration/relations/test_peers.py, tests/integration/test_tls.py, tests/integration/test_upgrade.py
Not using the testing profile.
Using the testing profile.
=> [MISC] Setting profiles

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/postgresql_k8s/v0/postgresql.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/relations/test_db.py
* Indico switched to data_interfaces
* No other tests test blocking on extensions in legacy interface
Port the split test from PG
=> [DPE-2844] Split indico and extension blocking tests

metadata.yaml
=> [DPE-3040] Update Rock

lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, poetry.lock, pyproject.toml, src/relations/db.py, src/relations/peers.py, src/relations/pgbouncer_provider.py, tests/integration/helpers/helpers.py, tests/integration/relations/test_db.py, tests/unit/relations/test_pgbouncer_provider.py, tests/unit/test_charm.py
=> Remove username secret

charmcraft.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, metadata.yaml
=> [MISC] Enable arm64

.github/codecov.yml, .github/renovate.json5, .github/workflows/ci.yaml, .gitignore, poetry.lock, pyproject.toml, tests/unit/relations/test_db.py, tox.ini
Update renovate config and enable codecov
=> [MISC] Renovate tweaks and enable codecov

metadata.yaml
=> [MISC] Update rock

.github/renovate.json5, lib/charms/data_platform_libs/v0/upgrade.py, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/postgresql_k8s/v0/postgresql_tls.py
* Update libs
* Add renovate regex for microk8s
=> [MISC] Update microk8s in renovate

.github/workflows/ci.yaml, src/charm.py, src/relations/db.py, src/relations/pgbouncer_provider.py, templates/logrotate.j2, templates/pgb_config.j2, tests/unit/relations/test_db.py, tests/unit/relations/test_pgbouncer_provider.py, tests/unit/test_charm.py
Add support for wildcard databases
VM PRs implementing the same functionality:
* https://github.com/canonical/pgbouncer-operator/pull/210
* https://github.com/canonical/pgbouncer-operator/pull/228
* https://github.com/canonical/pgbouncer-operator/pull/251
* https://github.com/canonical/pgbouncer-operator/pull/257
=> [DPE-4642] Multiple databases

lib/charms/postgresql_k8s/v0/postgresql.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/test_upgrade.py, tests/integration/test_upgrade_from_stable.py
Tests started timing out while deploying Postgresql
* Increase timeouts
* Bump charm libs
=> [MISC] Increase PG deploy timeouts

lib/charms/postgresql_k8s/v0/postgresql.py
=> [MISC] Update charm libs

lib/charms/tempo_k8s/v2/tracing.py, tests/integration/helpers/ha_helpers.py, tests/integration/helpers/helpers.py, tests/integration/relations/pgbouncer_provider/helpers.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/test_node_port.py, tests/integration/test_tls.py, tests/integration/test_trust.py, tests/integration/test_upgrade.py, tests/integration/test_upgrade_from_stable.py
Switch test-app interface from `first-database` to `database`
Update libs
=> [MISC] Switch test app interface

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/tempo_k8s/v1/charm_tracing.py, metadata.yaml
* Switch to charmed-pgbouncer-rock
* Update charm libs
=> [DPE-5145] Switch to charmed-pgbouncer-rock

lib/charms/tempo_k8s/v1/charm_tracing.py, src/relations/pgbouncer_provider.py, tests/integration/relations/pgbouncer_provider/helpers.py
=> [MISC] Add URI

metadata.yaml
Add rock tag and renovate comment.
=> [MISC] Add rock tag for renovate

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/relations/db.py, src/relations/pgbouncer_provider.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/relations/test_backend_database.py, tests/integration/relations/test_db.py, tests/integration/relations/test_db_admin.py, tests/integration/relations/test_peers.py, tests/integration/test_node_port.py, tests/integration/test_tls.py, tests/integration/test_trust.py, tests/integration/test_upgrade.py, tests/integration/test_upgrade_data_integrator.py, tests/integration/test_upgrade_from_stable.py
* Update libs
* Fixes to the node port logic
* Add PVC error workaround
=> [DPE-5205] Port PVC error test workaround and nodeport fixes

.github/workflows/release.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/tempo_k8s/v2/tracing.py
Lib release job also uses charmcraft
=> [MISC] Disable tox requirements generation for lib release

lib/charms/data_platform_libs/v0/data_models.py, lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, src/charm.py, src/config.py, src/relations/backend_database.py, src/relations/db.py, src/relations/peers.py, src/relations/pgbouncer_provider.py, tests/integration/helpers/helpers.py, tests/integration/relations/test_db_admin.py, tests/integration/test_charm.py, tests/integration/test_config.py, tests/integration/test_trust.py, tests/unit/relations/test_backend_database.py, tests/unit/relations/test_db.py, tests/unit/relations/test_peers.py, tests/unit/relations/test_pgbouncer_provider.py, tests/unit/test_charm.py, tox.ini
* Switch to Pydantic configuration
* Tweaks to the legacy relation
=> [MISC] Switch to typed charm and fixes

.github/workflows/ci.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/postgresql_k8s/v0/postgresql_tls.py, poetry.lock, pyproject.toml
=> [MISC] Enable Juju 3.6

lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/postgresql_k8s/v0/postgresql_tls.py, src/charm.py, src/constants.py, src/relations/peers.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
A more general fix to secrets resetting
Port of https://github.com/canonical/postgresql-operator/pull/726
=> [DPE-6320][DPE-6325] General secrets resetting fix

src/grafana_dashboards/pgbouncer-metrics.json
Port of https://github.com/canonical/pgbouncer-operator/pull/438
=> [MISC] Port COS polishings

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/data_platform_libs/v0/data_models.py, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py
=> [MISC] Update libs

concierge.yaml, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, tests/integration/test_config.py, tests/integration/test_trust.py
* Update charm libs
* Enable RBAC plugin on tests
=> [MISC] Enable RBAC in tests

.github/workflows/release.yaml
Release flow was moved.
Move to the new flow and hope that it works.
=> [MISC] Try to fix release
